### ISSUE TITLE
Can't connect to Kibana

### ISSUE THREAD

**Issue by m-titov** [AntonShuvaev/elasticsearch4idea#101]
Connection error:
`Connection test failed: org.elasticsearch4idea.dC: POST https://kibana.mgmt.support/api
/console/proxy?path=%2F&method=GET 400 {"error":{"root_cause":[{"type":"parse_exception","reason"
:"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status"
:400}`

**Comment by AntonShuvaev** [comment]
What version of Kibana do you use?

**Comment by m-titov** [comment]
it's OpenSearch 1.3.2

**Comment by AntonShuvaev** [comment]
I've released an update that should fix this issue. Can you check and let me know if it works for you?

**Comment by m-titov** [comment]
Still can't connect.
Same error for https://plugins.jetbrains.com/plugin/14512-elasticsearch/versions/stable/313328

**Comment by AntonShuvaev** [comment]
Is it AWS or self-hosted OpenSearch Dashboards?

**Comment by m-titov** [comment]
AWS

**Comment by AntonShuvaev** [comment]
Can you provide steps to reproduce? I tried to reproduce it but couldn't.
