### ISSUE TITLE
"indices" as disappeared on some of my clusters 

### ISSUE THREAD

**Issue by lazeyliu** [AntonShuvaev/elasticsearch4idea#148]
plugin version: 2024.1.0-233
elasticsearch version : 6.8.23

![image](https://github.com/AntonShuvaev/elasticsearch4idea/assets/5097837/8609c5c6-acd7-46b8-aa6a-a87eac15ac0c)

```
2024-03-21 17:12:04,161 [4131919]   FINE - #org.elasticsearch4idea.lH - GET http://10.168.81.14:9500/_data_stream/*?expand_wildcards=open 405 {"error":"Incorrect HTTP method for uri [/_data_stream/*?expand_wildcards=open] and method [GET], allowed: [POST]","status":405}
org.elasticsearch4idea.ex: GET http://10.168.81.14:9500/_data_stream/*?expand_wildcards=open 405 {"error":"Incorrect HTTP method for uri [/_data_stream/*?expand_wildcards=open] and method [GET], allowed: [POST]","status":405}
	at org.elasticsearch4idea.lk$a.a(SourceFile:577)
	at org.elasticsearch4idea.lk$a.a(SourceFile:572)
	at org.elasticsearch4idea.lk$j.a(SourceFile:300)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.elasticsearch4idea.lk$k.invoke(SourceFile:328)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q$b.invoke(SourceFile:69)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q.b(SourceFile:49)
	at org.elasticsearch4idea.q.a(SourceFile:57)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-21 17:12:04,162 [4131920]   FINE - #org.elasticsearch4idea.lH - GET http://10.168.81.14:9500/_cat/indices/*?format=json&expand_wildcards=open 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
org.elasticsearch4idea.ex: GET http://10.168.81.14:9500/_cat/indices/*?format=json&expand_wildcards=open 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
	at org.elasticsearch4idea.lk$a.a(SourceFile:577)
	at org.elasticsearch4idea.lk$a.a(SourceFile:572)
	at org.elasticsearch4idea.lk$b.handleResponse(SourceFile:558)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.elasticsearch4idea.lk$k.invoke(SourceFile:328)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q.b(SourceFile:49)
	at org.elasticsearch4idea.q.a(SourceFile:57)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-21 17:12:05,355 [4133113]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
```

**Comment by AntonShuvaev** [comment]
Thanks for reporting this. I'll look into it.

**Comment by AntonShuvaev** [comment]
The issue has been fixed. Please update to the version 2024.1.1

**Comment by lazeyliu** [comment]
emm... ,When I click the "refresh" button for the first time,"indices" still doesn't appear, when I click the "refresh" button for the second time,"indices" appears, and I get the following error on the first click:
```
2024-03-25 09:56:18,926 [ 103939]   FINE - #org.elasticsearch4idea.lH - GET http://10.168.81.14:9500/_cat/indices/*?format=json&expand_wildcards=open 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
org.elasticsearch4idea.ex: GET http://10.168.81.14:9500/_cat/indices/*?format=json&expand_wildcards=open 400 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
	at org.elasticsearch4idea.lk$a.a(SourceFile:596)
	at org.elasticsearch4idea.lk$a.a(SourceFile:591)
	at org.elasticsearch4idea.lk$b.handleResponse(SourceFile:577)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.elasticsearch4idea.lk$k.invoke(SourceFile:347)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q$b.invoke(SourceFile:69)
	at org.elasticsearch4idea.q.a(SourceFile:24)
	at org.elasticsearch4idea.q.b(SourceFile:49)
	at org.elasticsearch4idea.q.a(SourceFile:57)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by AntonShuvaev** [comment]
@lazeyliu, just released version 2024.1.2 with a new fix for the bug. Sorry for the oversight. Please try it and let me know if it works now.

**Comment by lazeyliu** [comment]
> @lazeyliu, just released version 2024.1.2 with a new fix for the bug. Sorry for the oversight. Please try it and let me know if it works now.

Yes, It works , thanks
