### ISSUE TITLE
Plugin hangs after update

### ISSUE THREAD

**Issue by jarkt** [AntonShuvaev/elasticsearch4idea#26]
After an update to 0.7.1 the plugin hangs when you switch to View Mode "Text". There is no reaction anymore from the IDE.

**Comment by AntonShuvaev** [comment]
Hi,

Does this bug appear constantly or sometimes? What IDE and OS do you use?

**Comment by AntonShuvaev** [comment]
Do you use 2020.1 and macOS? There is a platform bug related to macOS Big Sur https://youtrack.jetbrains.com/issue/IDEA-244962 which was fixed in 2020.2.1. It causes hangs that you described. Unfortunately, I can't fix this.  I've removed 2020.1 from compatible versions. You can download version 0.6.0 from [versions](https://plugins.jetbrains.com/plugin/14512-elasticsearch/versions/stable/106575) and install it manually.

**Comment by jarkt** [comment]
It's constantly. Then I have downgraded manually to 0.7.0 as it was running fine before. But, no idea why, same problem persists. I've recreated the connection configuration, but no success.

I'm using 2020.2.2 under Linux Mint.

**Comment by AntonShuvaev** [comment]
Can you provide IDE logs related to this problem? https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by jarkt** [comment]
It seems there are no related log messages. But this is the full log from the start of the IDE until just before the crash.
I've seen in the bottom right corner that there was starting a request:
![grafik](https://user-images.githubusercontent.com/2691295/105491748-1c63b880-5cb7-11eb-9b0f-1d90c9a847b5.png)

> 2021-01-22 13:27:28,466 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2021-01-22 13:27:28,494 [     28]   INFO -        #com.intellij.idea.Main - IDE: PhpStorm (build #PS-202.7319.77, 23 Sep 2020 16:28) 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - OS: Linux (5.4.0-58-generic, amd64) 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - JRE: 11.0.8+10-b944.31 (JetBrains s.r.o.) 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - JVM: 11.0.8+10-b944.31 (OpenJDK 64-Bit Server VM) 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx2048m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -XX:CICompilerCount=2 -Dsun.io.useCanonPrefixCache=false -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Djdk.attach.allowAttachSelf=true -Dkotlinx.coroutines.debug=off -Djdk.module.illegalAccess.silent=true -Dawt.useSystemAAFontSettings=lcd -Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine -Dsun.tools.attach.tmp.only=true -Dide.no.platform.update=true -XX:ErrorFile=/home/jark/java_error_in_PHPSTORM_%p.log -XX:HeapDumpPath=/home/jark/java_error_in_PHPSTORM.hprof -Didea.vendor.name=JetBrains -Didea.paths.selector=PhpStorm2020.2 -Djb.vmOptionsFile=/home/jark/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.7319.77.vmoptions -Didea.platform.prefix=PhpStorm 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - library path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - boot library path: /home/jark/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.7319.77/jbr/lib 
2021-01-22 13:27:28,495 [     29]   INFO -        #com.intellij.idea.Main - locale=de_DE JNU=UTF-8 file.encoding=UTF-8
  idea.config.path=/home/jark/.config/JetBrains/PhpStorm2020.2
  idea.system.path=/home/jark/.cache/JetBrains/PhpStorm2020.2
  idea.plugins.path=/home/jark/.local/share/JetBrains/PhpStorm2020.2
  idea.log.path=/home/jark/.cache/JetBrains/PhpStorm2020.2/log 
2021-01-22 13:27:28,553 [     87]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 57 ms 
2021-01-22 13:27:29,062 [    596]   INFO - llij.ide.plugins.PluginManager - /home/jark/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.7319.77/plugins/editorconfig overrides /home/jark/.local/share/JetBrains/PhpStorm2020.2/editorconfig 
2021-01-22 13:27:29,544 [   1078]   INFO - ntellij.idea.ApplicationLoader - CPU cores: 24; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@55e53027[Running, parallelism = 23, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@6ee3d51b 
2021-01-22 13:27:29,579 [   1113]   INFO - ntellij.idea.ApplicationLoader - WM detected: Mutter (Muffin) 
2021-01-22 13:27:29,594 [   1128]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: IDEA CORE (202.7319.77), com.intellij.platform.images (202.7319.77), HTML Tools (202.7319.77), Perforce (202.7319.77), Refactor-X (202.7319.77), Subversion (202.7319.77), XPathView + XSLT (202.7319.77), IDE Settings Sync (202.7319.77), Apache config (.htaccess) (202.7319.77), Configuration Script (202.7319.77), Copyright (202.7319.77), UML (202.7319.77), Machine Learning Code Completion (202.7319.77), Task Management (202.7319.77), Time Tracking (202.7319.77), ASP (202.7319.77), Ini (202.7319.77), FTP/SFTP Connectivity (ex. Remote Hosts Access) (202.7319.77), File Watchers (202.7319.77), CSS (202.7319.77), W3C Validators (202.7319.77), Less (202.7319.77), Sass (202.7319.77), Gherkin (202.7319.77), Mercurial (202.7319.77), Hunspell (202.7319.77), EditorConfig (202.7319.77), Haml (202.7319.77), GNU GetText files support (*.po) (202.7319.77), ReStructuredText (202.7319.77), Terminal (202.7319.77), Git (202.7319.77), ChangeReminder (202.7319.77), GitHub (202.7319.77), Performance Testing (202.7319.77), SSH Remote Run (202.7319.77), Shell Script (202.7319.77), TextMate Bundles (202.7319.77), Vagrant (202.7319.77), YAML (202.7319.77), Docker (202.7319.77), Settings Repository (202.7319.77), IntelliLang (202.7319.77), Markdown (202.7319.77), Grazie (202.7319.77), JavaScript and TypeScript (202.7319.77), JavaScript Intention Power Pack (202.7319.77), JavaScript Debugger (202.7319.77), Node.js (202.7319.77), Vue.js (202.7319.77), TSLint (202.7319.77), Angular and AngularJS (202.7319.77), Database Tools and SQL (202.7319.77), CoffeeScript (202.7319.77), HTTP Client (202.7319.77), PHP (202.7319.77), Joomla! (202.7319.77), Phing (202.7319.77), PHP Markdown Integration (202.7319.77), PHPT Support (202.7319.77), Blade (202.7319.77), DQL (202.7319.77), PhpStorm Workshop (202.7319.77), Command Line Tool (202.7319.77), Drupal (202.7319.77), WordPress (202.7319.77), PHP Remote Interpreter (202.7319.77), PHP Docker (202.7319.77), Behat Support (202.7319.77), Codeception Framework (202.7319.77), PHPSpec BDD Framework (202.7319.77), Twig (202.7319.77), PHP Grazie Integration (202.7319.77) 
2021-01-22 13:27:29,594 [   1128]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Elasticsearch (0.7.0), Makefile support (3.5.2), PHP Annotations (7.1.3), Symfony Support (0.21.204), .env files support (2020.3) 
2021-01-22 13:27:29,775 [   1309]   INFO - m.intellij.util.io.StorageLock - lower=100; upper=500; buffer=10; max=1959 
2021-01-22 13:27:29,788 [   1322]   INFO - tellij.util.io.FileChannelUtil - un-interruptible FileChannel-s will be used for indexes 
2021-01-22 13:27:29,852 [   1386]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2021-01-22 13:27:29,891 [   1425]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=13, fontScale=1.0; restored: fontSize=13, fontScale=1.0 
2021-01-22 13:27:29,945 [   1479]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=org.jetbrains.plugins.phpstorm.PhpStormInitialConfigurator) 
2021-01-22 13:27:29,960 [   1494]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2021-01-22 13:27:29,971 [   1505]   INFO - cloudConfig.CloudConfigManager - === Start: JBA_NOT_CONNECTED (1ms) === 
2021-01-22 13:27:29,973 [   1507]   INFO - cloudConfig.CloudConfigManager - === Start.updateInitStatus === 
2021-01-22 13:27:29,976 [   1510]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2021-01-22 13:27:29,982 [   1516]   INFO - tellij.ide.SystemHealthMonitor - restored ignored PIPE handler 
2021-01-22 13:27:29,984 [   1518]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus === 
2021-01-22 13:27:30,047 [   1581]   INFO - penapi.application.Experiments - Experimental features enabled for user: wsl.p9.support, wsl.p9.show.roots.in.file.chooser, inline.browse.button, linux.native.menu, recent.and.edited.files.together, show.create.new.element.in.popup, copy.reference.popup, new.large.text.file.viewer, terminal.shell.command.handling 
2021-01-22 13:27:30,048 [   1582]   INFO - BridgeProjectLifecycleListener - Using legacy project model to open project 
2021-01-22 13:27:30,050 [   1584]   INFO - penapi.wm.impl.GlobalMenuLinux - can't start main loop via JavaFX (will run it manually): com.sun.javafx.application.PlatformImpl 
2021-01-22 13:27:30,134 [   1668]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /home/jark/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.7319.77/bin/fsnotifier64 
2021-01-22 13:27:30,144 [   1678]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2021-01-22 13:27:30,213 [   1747]   INFO - penapi.wm.impl.GlobalMenuLinux - created instance of GlobalMenuLinux for xid=0x500004d 
2021-01-22 13:27:30,393 [   1927]   INFO - .cloudConfig.CloudConfigClient - === Get cloud config URL: https://cloudconfig.jetbrains.com/cloudconfig/files === 
2021-01-22 13:27:30,588 [   2122]   INFO - pl.projectlevelman.NewMappings - VCS Root: [Git] - [/mnt/data/webdev/p1/api] 
2021-01-22 13:27:30,665 [   2199]   INFO - rojectCodeStyleSettingsManager - Loading Project code style 
2021-01-22 13:27:30,677 [   2211]   INFO - eStyle.CustomCodeStyleSettings - Loaded com.jetbrains.php.lang.formatter.PhpCodeStyleSettings 
2021-01-22 13:27:30,677 [   2211]   INFO - eStyle.CustomCodeStyleSettings - Loaded com.intellij.psi.css.codeStyle.CssCodeStyleSettings 
2021-01-22 13:27:30,678 [   2212]   INFO - eStyle.CustomCodeStyleSettings - Loaded com.intellij.lang.javascript.formatter.JSCodeStyleSettings 
2021-01-22 13:27:30,680 [   2214]   INFO - eStyle.CommonCodeStyleSettings - Loaded JSON common code style settings 
2021-01-22 13:27:30,680 [   2214]   INFO - eStyle.CommonCodeStyleSettings - Loaded JavaScript common code style settings 
2021-01-22 13:27:30,702 [   2236]   INFO - eStyle.CommonCodeStyleSettings - Loaded PHP common code style settings 
2021-01-22 13:27:30,702 [   2236]   INFO - eStyle.CommonCodeStyleSettings - Loaded SCSS common code style settings 
2021-01-22 13:27:30,703 [   2237]   INFO - eStyle.CommonCodeStyleSettings - Loaded Twig common code style settings 
2021-01-22 13:27:30,703 [   2237]   INFO - eStyle.CommonCodeStyleSettings - Loaded YAML common code style settings 
2021-01-22 13:27:30,718 [   2252]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus.value: JBA_NOT_CONNECTED === 
2021-01-22 13:27:30,745 [   2279]   INFO - leBasedIndexDataInitialization - Initialization done: 957 
2021-01-22 13:27:30,779 [   2313]   INFO - exImpl$StubIndexInitialization - Initialization done: 33 
2021-01-22 13:27:31,166 [   2700]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2021-01-22 13:27:32,251 [   3785]   INFO -              PerformancePlugin - Performance Plugin is in silent mode 
2021-01-22 13:27:32,277 [   3811]   INFO - cloudConfig.CloudConfigManager - === StatusBar.update another widget: null === 
2021-01-22 13:27:32,277 [   3811]   INFO - cloudConfig.CloudConfigManager - === End.updateInitStatus === 
2021-01-22 13:27:32,384 [   3918]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 2 millis (read time: 1) 
2021-01-22 13:27:32,384 [   3918]   INFO -  #git4idea.commands.GitHandler - [.] git version 
2021-01-22 13:27:32,391 [   3925]   INFO -  #git4idea.commands.GitHandler - git version 2.25.1 
2021-01-22 13:27:32,397 [   3931]   INFO - ea.config.GitExecutableManager - Git version for /usr/bin/git: 2.25.1.0 (UNIX) 
2021-01-22 13:27:32,592 [   4126]   INFO - ProjectRootPostStartUpActivity - /mnt/data/webdev/p1/api/.idea case-sensitivity: expected=true actual=true 
2021-01-22 13:27:32,618 [   4152]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 346ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:33,094 [   4628]   INFO - cloudConfig.CloudConfigManager - === StatusBar.start create === 
2021-01-22 13:27:33,426 [   4960]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 3395 ms 
2021-01-22 13:27:33,532 [   5066]   INFO - llij.database.util.SqlDialects - SQL dialects initialized in 0 ms 
2021-01-22 13:27:33,973 [   5507]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 474ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:34,002 [   5536]   INFO - ndex.PrebuiltIndexProviderBase - Using prebuilt id-index from /home/jark/.cache/JetBrains/PhpStorm2020.2/index/.persistent/prebuilt/PHP/id-index.input 
2021-01-22 13:27:34,492 [   6026]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 518ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:34,497 [   6031]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 5 files to index 
2021-01-22 13:27:34,499 [   6033]   INFO - indexing.UnindexedFilesUpdater - Using 4 threads for indexing 
2021-01-22 13:27:34,516 [   6050]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 19ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:34,612 [   6146]   INFO - omposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json 
2021-01-22 13:27:34,617 [   6151]   INFO - omposerSettingSyncConfigClient - Composer synchronization is enabled -> update IDE settings based on composer.json 
2021-01-22 13:27:34,719 [   6253]   INFO - pl.ProjectRootManagerComponent - project roots have changed (trace_hash = 1854174870) 
java.lang.Throwable
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.synchronizeRoots(ProjectRootManagerComponent.java:306)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireRootsChangedEvent(ProjectRootManagerComponent.java:210)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:428)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:37)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:96)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:371)
	at com.jetbrains.php.config.library.PhpAdditionalLibraryManager.lambda$fireLibraryChanged$4(PhpAdditionalLibraryManager.java:184)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.jetbrains.php.config.library.PhpAdditionalLibraryManager.lambda$fireLibraryChanged$5(PhpAdditionalLibraryManager.java:184)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:221)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:207)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:221)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$unsafeRunWhenSmart$1(DumbServiceImpl.java:224)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-01-22 13:27:35,191 [   6725]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 403ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:36,284 [   7818]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1093ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:36,288 [   7822]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 0 files to index 
2021-01-22 13:27:36,297 [   7831]   INFO - pl.ProjectRootManagerComponent - project roots have changed (trace_hash = 425348156) 
java.lang.Throwable
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.synchronizeRoots(ProjectRootManagerComponent.java:306)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireRootsChangedEvent(ProjectRootManagerComponent.java:210)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:428)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:37)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:96)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:371)
	at com.jetbrains.php.config.library.PhpAdditionalLibraryManager.lambda$fireLibraryChanged$4(PhpAdditionalLibraryManager.java:184)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.jetbrains.php.config.library.PhpAdditionalLibraryManager.lambda$fireLibraryChanged$5(PhpAdditionalLibraryManager.java:184)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:221)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:207)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:348)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:340)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-01-22 13:27:36,420 [   7954]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 109ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:36,450 [   7984]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 30ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:36,458 [   7992]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 2 files to index 
2021-01-22 13:27:36,458 [   7992]   INFO - indexing.UnindexedFilesUpdater - Using 4 threads for indexing 
2021-01-22 13:27:36,605 [   8139]   INFO - ndex.PrebuiltIndexProviderBase - Using prebuilt sdk-stubs from /home/jark/.cache/JetBrains/PhpStorm2020.2/index/.persistent/prebuilt/PHP/sdk-stubs.input 
2021-01-22 13:27:36,642 [   8176]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 184ms; general responsiveness: ok; EDT responsiveness: ok 
2021-01-22 13:27:45,036 [  16570]   INFO - nSession$CountedThreadExecutor - DbSrcWriter stopped 
2021-01-22 13:27:47,257 [  18791]   INFO - j.ide.actions.RevealFileAction - Timed out 
2021-01-22 13:27:47,257 [  18791]   INFO - j.ide.actions.RevealFileAction - Nemo-Share-Message: 13:27:37.723: Called "net usershare info" but it failed: »net usershare« gab den Fehler 255 zurück: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Datei oder Verzeichnis nicht gefunden
Please ask your system administrator to enable user sharing.

**Comment by AntonShuvaev** [comment]
Fixed in 0.7.2
