### ISSUE TITLE
Constantly losing config

### ISSUE THREAD

**Issue by cnpatric** [AntonShuvaev/elasticsearch4idea#82]
Hey,

Pretty much every time I restart Webstorm i lose almost all configs, I have to reenter all my connection details. 
This is incredibly frustrating to build a query and then have it disappear.

Please advise on how to support you with data to get rid of this issue:

WebStorm 2022.1
Elasticsearch Plugin 2022.2.0-221

Having to reenter my connection details also completely purges my request history...

Also having no other option but "delete" here is very counter intuitive:

![image](https://user-images.githubusercontent.com/82205245/180783661-ab4efb2b-f754-4c1f-af5d-06021b1258c9.png)

I should be able to double click and jump to the query instead of having to double click the query in the project view

**Comment by AntonShuvaev** [comment]
Hi,

Thanks for reporting this.  I will take a look at it.

**Comment by AntonShuvaev** [comment]
Fixed in 2022.2.1

**Comment by christopher-johnson** [comment]
This issue still exists with IntelliJ on MacOS.  Reported via the IDE Internal Errors interface.

com.intellij.diagnostic.PluginException: Cannot init component state (componentName=GlobalElasticsearchConfiguration, componentClass=K) [Plugin: org.elasticsearch4idea]

Caused by: java.lang.IllegalArgumentException: Illegal base64 character 7b
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)

**Comment by AntonShuvaev** [comment]
Hi, can you try to restart IDE one more time. After the first start GlobalElasticsearchConfiguration is read in the old way with base64 decoding for backward compatibility. Then plugin will save GlobalElasticsearchConfiguration without base64 encoding and with property `version=1`. You can check it in configuration file `/Users/{user}/Library/Application Support/JetBrains/IntelliJIdea2022.2/options/globalElasticsearchSettings.xml'`. After the restart the problem should gone.

**Comment by christopher-johnson** [comment]
I was able to resolve the problem by manually removing the previous configurations from that file and then recreating the connections in the interface.  Thanks.
