### ISSUE TITLE
url encoded ids in path

### ISSUE THREAD

**Issue by nick-bir** [AntonShuvaev/elasticsearch4idea#98]
If id contains symbols that require url encoding plugin doesn't process it correctly:
With url encoding:
`GET my-index/_doc/slash%2Fid`
response:
`{..., "_id": "slash%2Fid", "found": "false"}

Without url encoding:
`GET my-index/_doc/slash/id`
response:
`"error": "no handler found for uri [/my-index/_doc/slash/id] and method [GET]"`

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue, will fix it in the next release.

**Comment by AntonShuvaev** [comment]
Fixed. Now you can use whitespaces in urls

**Comment by nick-bir** [comment]
Sorry, Anton, but I still can't use slashes in urls. I get the same error

**Comment by AntonShuvaev** [comment]
Sorry, I misunderstood the issue. I've fixed it now by disabling urlencoding the url, so you can use %2F in the url.
You can download the version with the fix here: https://plugins.jetbrains.com/files/14512/306934/Elasticsearch-2023.1.3-223-signed.zip and install it manually or wait until it will be available in marketplace.

**Comment by nick-bir** [comment]
Just checked now - it works, thanks!
